# Numpy

numpy gunanya untuk handle data tipe numerik
Numpy array adal data srtuktur yg memudahkan operasi seputar numerik, formula matematik, dll
Numpy array dapat diakses dengan menggunakan index, seperti array biasa

In [3]:
import numpy as np

In [3]:
arr = np.array([70,80,90])
print(arr, type(arr)) 

[70 80 90] <class 'numpy.ndarray'>


nd - n dimensional

n dimemsional artinya, numpy array bisa memiliki lebih dari 1 dimensi. bisa ada array dalam array(2 dimensi), dst.
untuk check pakai .shape

In [4]:
arr.shape

(3,)

arr = 1 dimensi, isinya 3 item

In [5]:
arr_nilai = np.array([
    [45, 55, 65],
    [25,89, 68]
])

print(arr_nilai)

[[45 55 65]
 [25 89 68]]


In [6]:
print(arr_nilai.shape)

(2, 3)


arr_nilai punya 2 dimensi, 2 item pada dimensi I & 3 item pada dimensi II

jumlah item di setiap dimensi harus sama, jika tidak seimbang tidak bisa di baca

In [9]:
#latihan pendek
#buat numpy array , isi angka urut 5 sampai 10
#buat lagi numpy array 2 dimensi, isi dengan 3 baris angka, masing-masing 3 kolom. 11 - 19

arr1 = np.array([
    5, 6, 7, 8, 9, 10
])

arr2 = np.array([[11, 12, 13],
                  [14, 15, 16],
                  [17, 18, 19]])

print(arr1)
print(arr2)

[ 5  6  7  8  9 10]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [11]:
print(arr1.shape)
print(arr2.shape)

(6,)
(3, 3)


selain np.array() :
1. .zeros() : otomatis isi 0
2. .ones() : otomatis isi 1
3. .arrange() : otomatis angka urut

.random.default_rng() : isi angka random

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr3 = np.array([
    1,2,3,4,5
])

np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
rng = np.random.default_rng()

rng.random(10)

array([0.26676295, 0.60120045, 0.32878209, 0.61725559, 0.30050351,
       0.46266321, 0.59660737, 0.49290138, 0.90417942, 0.76515557])

In [15]:
#buat dummy data 10 murid nilai antara 50 - 90
rng = np.random.default_rng()

nilai = rng.random(10) * 40 + 50
nilai = nilai.astype(int)

print(nilai)


[72 64 74 86 70 76 62 84 79 66]


In [28]:
#latihan pendek
#buatlah 100 angka random hasil lempar dadu. BIsa bernilai 1,2,3,4,5,6
#hitung hasil rata-rata lempar dadu
#buatlah dadu ke-2 pada var berbeda , jumlah 100
#jumlahkan kedua hasil seperti hasil 2 dadu sekaligus
#hitung rata2 lempar 2 dadu

dadu1 = rng.random(100) * 6
dadu1 = dadu1.astype(int) + 1
rata1 = np.mean(dadu1)

dadu2 = rng.random(100) * 6
dadu2 = dadu2.astype(int) + 1
tambah = dadu1 + dadu2
rata2 = np.mean(tambah)

print(rata1)
print(rata2)

3.72
7.31


CRUD 
- Create
- Read
- Update
- Delete

In [32]:
dadu3 = (rng.random(5) * 6 + 1).astype(int)
print(dadu3)

[1 4 1 3 6]


In [33]:
dadu3 = np.append(dadu3, [3])
print(dadu3)

[1 4 1 3 6 3]


In [34]:
arr = np.arange(24).reshape((3,8))
print(arr)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [35]:
arr = np.arange(24).reshape((4, 6))
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [36]:
arr = np.arange(24).reshape((6,4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [37]:
#Indexing & slicing
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [38]:
arr[1,1]

5

In [39]:
arr[1,2]

6

In [40]:
arr[0, 1:4]

array([1, 2, 3])

In [41]:
# : artinya semua baris
arr[:, 1]

array([ 1,  5,  9, 13, 17, 21])

In [42]:
#copy & view
arr = np.arange(24).reshape((3,8))
arr = arr.reshape((3,8))

In [43]:
print(arr)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [46]:
#ambil angka 3, 11, 19
print(arr[0,3])
print(arr[1,3])
print(arr[2,3])

3
11
19


In [48]:
#ambil angka 15, 16
print(arr[1, -1])
print(arr[2,0])

15
16


In [49]:
#latihan slicing 11,12,19,20 satu kali slicing
# [1,3][1,4]
# [2,3][2,4]

print(arr[1:3, 3:5])

[[11 12]
 [19 20]]


In [50]:
#array operations
harga_roti = np.array([5000, 1500, 2750])
stok_roti = np.array([12, 36, 24])

harga_roti * stok_roti

array([60000, 54000, 66000])

In [54]:
#harga naik roti naik 1000
harga_roti = harga_roti + 1000

In [55]:
print(harga_roti)

[6000 2500 3750]


In [53]:
arr1 = (rng.random(3) * 7).astype(int)
arr2 = (rng.random(3) * 30 + 8).astype(int)

print(arr1 + arr2)

print(arr1 - arr2)

print(arr1 * arr2)

print(arr1 / arr2)

[15 24 32]
[ -9 -14 -26]
[36 95 87]
[0.25       0.26315789 0.10344828]


In [56]:
#agregasi
print(harga_roti.max(), "roti termahal")
print(harga_roti.min(), "roti termurah")
print(harga_roti.mean(), "rata2 harga roti")
print(harga_roti.sum(), "jumlah harga jika beli satu2")

6000 roti termahal
2500 roti termurah
4083.3333333333335 rata2 harga roti
12250 jumlah harga jika beli satu2


In [57]:
arr_angka = (rng.random(12) * 1000 + 1000).astype(int) / 10
arr_angka = arr_angka.reshape((3,4))
print(arr_angka)

[[110.2 123.7 158.3 134.1]
 [165.1 137.  138.5 191.1]
 [147.9 191.8 144.8 108.5]]


In [58]:
#max min mean sum
arr_angka.max(axis=0)
#axis = 0 artinya per kolom

array([165.1, 191.8, 158.3, 191.1])

In [59]:
arr_angka.max(axis=1)
#axis = 1 artinya per baris

array([158.3, 191.1, 191.8])

In [60]:
print(arr_angka.min())
print(arr_angka.min(axis=0))
print(arr_angka.min(axis=1))

108.5
[110.2 123.7 138.5 108.5]
[110.2 137.  108.5]


In [61]:
print(arr_angka.mean())
print(arr_angka.mean(axis=0))
print(arr_angka.mean(axis=1))

145.91666666666666
[141.06666667 150.83333333 147.2        144.56666667]
[131.575 157.925 148.25 ]


In [62]:
#Matrices

arr1 = np.array([[2,3], [4,5]])
arr2 = np.array([[7,8], [9,10]])

arr1 * arr2


array([[14, 24],
       [36, 50]])

In [63]:
#dot product

penjualan_roti = np.array([
                            [10,3,12],
                            [8,5,7],
                            [6,7,8],
                            [12,2,15],
                            [15,5,17],
                          ])

print(penjualan_roti)

[[10  3 12]
 [ 8  5  7]
 [ 6  7  8]
 [12  2 15]
 [15  5 17]]


In [64]:
harga_roti = np.array([
                        [5000],
                        [7000],
                        [3000],
                      ])

print(harga_roti)

[[5000]
 [7000]
 [3000]]


In [66]:
total_penjualan = penjualan_roti.dot(harga_roti)
print(total_penjualan)

[[107000]
 [ 96000]
 [103000]
 [119000]
 [161000]]


In [67]:
print(total_penjualan.min(), total_penjualan.max(), total_penjualan.mean())

96000 161000 117200.0


In [68]:
#transpose vs reshape
print(penjualan_roti.T)

[[10  8  6 12 15]
 [ 3  5  7  2  5]
 [12  7  8 15 17]]


In [ ]:
print(penjualan_roti.reshape())

In [72]:
#buatlah sebuah numpy array menggunakan random antara 1 - 100
#lakukan reshape 2 dimensi, 10 baris & 10 kolom
#lakukan indexing untuk ambil angka 75
#gunakan aslicing untuk ambil 4 angka sekaligus 2x2

arr = np.array(rng.random(100) * 100 + 1).astype(int)
arr = arr.reshape(10,10)


In [76]:
print(arr)
print(arr[3,0])
print(arr[1:3, 3:5])

[[ 85  96   6  91  69  83  28   4   3  84]
 [ 61  92  34  81  92   9  23  83  54  13]
 [ 82  50  70  50  44   1  47  84   9  87]
 [ 75  96  52  91   1  92  50  17  35  59]
 [  8  47  20   5  36  61  14  57  28  30]
 [ 62  30  97  35  81  26  60  38 100 100]
 [ 97  69   6  85  85  49  45  90  58  31]
 [ 63  78  64  54  74  94  35  84  33  64]
 [ 14  34  14 100  60  82  33  51  15  45]
 [ 78  46  51  88  95  95  79  66  89  19]]
75
[[81 92]
 [50 44]]
